apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/sonarr-statefulset.yaml
  - resources/sonarr-service.yaml
  - resources/sonarr-gateway-route.yaml
  - resources/sonarr-cm.yaml

namespace: starrs

images:
  - name: sonarr-image
    newName: ghcr.io/home-operations/sonarr
    newTag: rolling@sha256:01db3e6a923f6e0f3a217baa94b4660cf2f9b45d4166b2fc8c20c67c5221cb78 ***REMOVED*** https://github.com/home-operations/containers/pkgs/container/sonarr
