apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/sonarr-statefulset.yaml
  - resources/sonarr-service.yaml
  - resources/sonarr-gateway-route.yaml
  - resources/sonarr-cm.yaml

namespace: starrs

images:
  - name: sonarr-image
    newName: ghcr.io/home-operations/sonarr
    newTag: rolling@sha256:67815effd2ea18398ffc2011d974b8b1cd3939eec5aa74688ffbf371ff65dd84 ***REMOVED*** https://github.com/home-operations/containers/pkgs/container/sonarr
