apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/radarr-statefulset.yaml
  - resources/radarr-service.yaml
  - resources/radarr-gateway-route.yaml
  - resources/radarr-cm.yaml

namespace: starrs

images:
  - name: radarr-image
    newName: ghcr.io/home-operations/radarr
    newTag: rolling@sha256:d380d69c729b4116d224ebb0b4909ff22395fc7b78e8a1976c43ae09430ffc5a ***REMOVED*** https://github.com/home-operations/containers/pkgs/container/radarr
