apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/qui-deployment.yaml
- resources/qui-services.yaml
- resources/qui-gateway-route.yaml

namespace: downloads

images:
- name: qui-image
  newName: ghcr.io/autobrr/qui
  newTag: v1.31.0@sha256:74ac327d7e0cad1309cbfe3d024bfc9e8136b9926a1450d2f6192c6970f66362 ***REMOVED*** https://github.com/autobrr/qui
