apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/qui-deployment.yaml
- resources/qui-services.yaml
- resources/qui-gateway-route.yaml

namespace: downloads

images:
- name: qui-image
  newName: ghcr.io/autobrr/qui
  newTag: v1.30.0@sha256:1172ca40283330445d61189263a65a31ba703770a230b9e2a913f6e57bc2dd23 ***REMOVED*** https://github.com/autobrr/qui
