apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/abs-statefulset.yaml
  - resources/abs-service.yaml
  - resources/abs-gateway-route.yaml
  - resources/abs-cm.yaml

namespace: audiobookshelf

images:
  - name: abs-image
    newName: ghcr.io/advplyr/audiobookshelf
    newTag: 2.36.0 ***REMOVED*** https://github.com/advplyr/audiobookshelf/pkgs/container/audiobookshelf
