apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lubelogger

resources:
  - resources/lubelogger-namespace.yaml
  - resources/lubelogger-gateway-route.yaml
  - resources/lubelogger-pvc.yaml
  - resources/lubelogger-service.yaml
  - resources/lubelogger-statefulset.yaml

generators:
  - ksops.yaml

generatorOptions:
  disableNameSuffixHash: true
