apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: open-webui

resources:
  - resources/open-webui-namespace.yaml
  - resources/open-webui-gateway-route.yaml
  - resources/open-webui-pvc.yaml
  - resources/open-webui-service.yaml
  - resources/open-webui-statefulset.yaml
