apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/jellyseerr-statefulset.yaml
- resources/jellyseerr-service.yaml
- resources/jellyseerr-gateway-route.yaml
- resources/jellyseerr-cm.yaml

namespace: starrs

images:
- name: jellyseerr-image
  newName: fallenbagel/jellyseerr
  newTag: 2.7.3 ***REMOVED*** https://hub.docker.com/r/fallenbagel/jellyseerr/tags
