apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/wowmin-namespace.yaml
  - resources/wowmin-pvc.yaml
  - resources/wowmin-deployment.yaml
  - resources/wowmin-service.yaml
  - resources/wowmin-gateway-route.yaml

generators:
  - ksops.yaml

generatorOptions:
  disableNameSuffixHash: true

namespace: wowmin

images:
  - name: wowmin-image
    newName: ghcr.io/example/wowmin
    newTag: 3.0.1@sha256:82b1dca2bfa9cc5b4b1c9aeb49b9dadca04b63523c90c2db1cae454c21522495
