apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/wowmin-namespace.yaml
  - resources/wowmin-pvc.yaml
  - resources/wowmin-deployment.yaml
  - resources/wowmin-service.yaml
  - resources/wowmin-gateway-route.yaml

generators:
  - ksops.yaml

generatorOptions:
  disableNameSuffixHash: true

namespace: wowmin

images:
  - name: wowmin-image
    newName: ghcr.io/example/wowmin
    newTag: 3.0.2@sha256:e0d25601073640ef4781637c8dfb5735ad2a5fc03621d42ef101812b9e4da918
