apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/azerothcore-discord-deployment.yaml
  - resources/azerothcore-namespace.yaml

generators:
  - ksops.yaml

generatorOptions:
  disableNameSuffixHash: true

namespace: azerothcore-discord

images:
  - name: azerothcore-discord-image
    newName: ghcr.io/example/azerothcore-discord
    newTag: 1.0.0 ***REMOVED*** https://github.com/Griznah/azerothcore-discord/tags
