apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/qbittorrent-statefulset.yaml
- resources/qbittorrent-services.yaml
- resources/qbittorrent-gateway-route.yaml
- resources/qbittorrent-cm.yaml

namespace: downloads

images:
- name: qbittorrent-image
  newName: ghcr.io/home-operations/qbittorrent
  newTag: rolling@sha256:9307627e03981d5473aa31175ea76ed56ea3752333ca49d601b6af45e281e7ba ***REMOVED*** https://github.com/home-operations/containers/pkgs/container/qbittorrent
