apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/bazarr-statefulset.yaml
- resources/bazarr-service.yaml
- resources/bazarr-gateway-route.yaml
- resources/bazarr-cm.yaml

namespace: starrs

images:
- name: bazarr-image
  newName: ghcr.io/home-operations/bazarr
  newTag: rolling@sha256:17dc1cff22e99694ffbfb06555526cb47a66b362b4d6c982f06b557f7caae2bb ***REMOVED*** https://github.com/home-operations/containers/pkgs/container/bazarr
***REMOVED***  newName: lscr.io/linuxserver/bazarr
***REMOVED***  newTag: v1.5.1-ls292 ***REMOVED*** https://github.com/linuxserver/docker-bazarr/releases
