***REMOVED******REMOVED******REMOVED******REMOVED*** Do not use this file, it is just for testing purposes
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: storage
  namespace: argo-system
  annotations:
    notifications.argoproj.io/subscribe.on-app-deleted.gmail: you@example.com
    notifications.argoproj.io/subscribe.on-health-degraded.gmail: you@example.com
    notifications.argoproj.io/subscribe.on-sync-failed.gmail: you@example.com
    notifications.argoproj.io/subscribe.on-sync-status-unknown.gmail: you@example.com
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: false
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: storage
  namespace: argo-system
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: git@github.com:Griznah/k8s-apps.git
        revision: main
        directories:
          - path: "storage/proxmox-csi-driver"
          ***REMOVED***- path: "storage/foo"
          - exclude: true
            path: "storage/*.disabled"
  syncPolicy:
    preserveResourcesOnDeletion: false
    applicationsSync: create-update
  template:
    metadata:
      name: "{{ .path.basenameNormalized }}"
      labels:
        app-group: storage
    spec:
      project: storage
      source:
        repoURL: git@github.com:Griznah/k8s-apps.git
        targetRevision: main
        path: "{{ .path.path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: { { index .path.segments 1 } }
      revisionHistoryLimit: 2
