apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: starrs
  namespace: argo-system
  annotations:
    notifications.argoproj.io/subscribe.on-app-deleted.gmail: you@example.com
    notifications.argoproj.io/subscribe.on-health-degraded.gmail: you@example.com
    notifications.argoproj.io/subscribe.on-sync-failed.gmail: you@example.com
    notifications.argoproj.io/subscribe.on-sync-status-unknown.gmail: you@example.com
  finalizers:
  - argocd.argoproj.io/resources-finalizer
spec:
  sourceRepos:
  - "*"
  destinations:
  - namespace: "*"
    server: "*"
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
  orphanedResources:
    warn: false
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: starrs
  namespace: argo-system
spec:
  generators:
  - git:
      repoURL: git@github.com:Griznah/k8s-apps.git
      revision: main
      directories:
      - path: "starrs/*"
      - exclude: true
        path: "starrs/*.disabled"
  syncPolicy:
    preserveResourcesOnDeletion: false
    applicationsSync: create-update
  template:
    metadata:
      name: "{{ path.basenameNormalized }}"
      labels:
        app-group: starrs
    spec:
      project: starrs
      source:
        repoURL: git@github.com:Griznah/k8s-apps.git
        targetRevision: main
        path: "{{ path }}"
      destination:
        server: https://kubernetes.default.svc
        namespace: starrs
      syncPolicy:
        managedNamespaceMetadata:
          labels:
            pod-security.kubernetes.io/audit: privileged
            pod-security.kubernetes.io/enforce: privileged
            pod-security.kubernetes.io/warn: privileged
          annotations:
            argocd.argoproj.io/sync-wave: "-10"
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        
      revisionHistoryLimit: 5
