apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/seerr-statefulset.yaml
- resources/seerr-service.yaml
- resources/seerr-gateway-route.yaml
- resources/seerr-cm.yaml

namespace: starrs

images:
- name: seerr-image
  newName: ghcr.io/seerr-team/seerr
  newTag: v3.4.0 ***REMOVED*** https://github.com/seerr-team/seerr/releases
