apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - resources/copyparty-namespace.yaml
  - resources/copyparty-deployment.yaml
  - resources/copyparty-service.yaml
  - resources/copyparty-gateway-route.yaml

generators:
  - ksops.yaml

generatorOptions:
  disableNameSuffixHash: true

namespace: copyparty

images:
  - name: copyparty-image
    newName: docker.io/copyparty/ac
    newTag: 1.20.25@sha256:8fb1a8f366085ca77cca31b235496e7c67c13cdc3cbedce1202e113e5c4b9e7e ***REMOVED*** https://hub.docker.com/r/copyparty/ac
