apiVersion: v1
kind: Service
metadata:
  namespace: starrs
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: flaresolverr
  name: flaresolverr
spec:
  ports:
    - name: "8191"
      port: 8191
      targetPort: 8191
  selector:
    io.kompose.service: flaresolverr
status:
  loadBalancer: {}
