apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: drag

resources:
  - resources/drag-namespace.yaml
  - resources/qdrant.yaml
  - resources/llama-embed.yaml
  - resources/drag-app.yaml
  - resources/open-webui.yaml
  - resources/drag-gateway-route.yaml
