apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - resources/unpackerr-deployment.yaml
***REMOVED***- resources/unpackerr-gateway-route.yaml

generators:
  - ksops.yaml

generatorOptions:
  disableNameSuffixHash: true

namespace: starrs

images:
  - name: unpackerr-image
    newName: golift/unpackerr
    newTag: v0.16.1 ***REMOVED*** https://github.com/Unpackerr/unpackerr/releases
