apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: absa-ac-dev

resources:
  - resources/absa-ac-namespace.yaml
  - resources/absa-ac-gateway-route.yaml
  - resources/absa-ac-pvc.yaml
  - resources/absa-ac-service.yaml
  - resources/absa-ac-statefulset.yaml

generators:
  - ksops.yaml

generatorOptions:
  disableNameSuffixHash: true
