resources:
  - resources/namespace.yaml
  - resources/schedules.yaml

generators:
  - ksops.yaml

generatorOptions:
  disableNameSuffixHash: true

helmCharts:
  - name: velero
    repo: https://vmware-tanzu.github.io/helm-charts/
    version: 12.1.0 ***REMOVED*** Velero 1.18.1 — https://artifacthub.io/packages/helm/vmware-tanzu/velero?modal=changelog
    releaseName: velero
    namespace: velero
    valuesFile: values.yaml
    includeCRDs: true
